
server:
  port: ${API_GATEWAY_SERVER_PORT}

spring:
  application:
    name: ${API_GATEWAY_APP_NAME}

  output:
    ansi:
      enabled: ALWAYS

  config:
    import: optional:configserver:${CONFIG_SERVER_URL}
